name: formz_test
description: Test utils for the formz library

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: '1.0.1+1'

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.1

  formz:
    git: ssh://git@github.com/TinDan-Dev/app-formz.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.5

  lint: ^1.5.3

  bloc_test: ^8.0.2

  g_formz:
    git: ssh://git@github.com/TinDan-Dev/app-g-formz.git